(function(){
angular.module('portfolio2017',[
    'ngRoute',
    'ngResource',
    'ngAnimate',
    'about-me',
    'portfolio',
    'apps',
    'chatbox',
    'admin-panel',
    'imagelistSrv',
    'appslistSrv',
    'chatboxSrv',
    'pagerSrv'
]);
})();